"""v3_initial_schema

Revision ID: 13eb36717947
Revises: 
Create Date: 2026-06-13 12:45:20.515166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13eb36717947'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('paused', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sandbox_id', sa.Text(), nullable=True),
    sa.Column('sandbox_status', sa.Text(), server_default='none', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("sandbox_status IN ('none', 'running', 'paused', 'error')", name='ck_projects_sandbox_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_user', 'projects', ['user_id'], unique=False)
    op.create_table('team_templates',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('engine', sa.Text(), nullable=False),
    sa.CheckConstraint("engine IN ('crew', 'agent_sdk')", name='ck_team_templates_engine'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('agent_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_key', sa.Text(), nullable=False),
    sa.Column('role_key', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('role_instructions', sa.Text(), nullable=False),
    sa.Column('default_tier', sa.Text(), nullable=False),
    sa.Column('is_starter', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('default_output_type', sa.Text(), nullable=True),
    sa.Column('default_output_target_role_key', sa.Text(), nullable=True),
    sa.Column('default_max_iterations', sa.Integer(), nullable=True),
    sa.CheckConstraint("default_output_type IS NULL OR default_output_type IN ('handoff', 'review_loop')", name='ck_agent_templates_output_type'),
    sa.CheckConstraint("default_tier IN ('strong', 'medium', 'light')", name='ck_agent_templates_tier'),
    sa.ForeignKeyConstraint(['template_key'], ['team_templates.key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_key', 'role_key', name='uq_agent_templates_role')
    )
    op.create_table('context_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('mime', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_bytes', sa.LargeBinary(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_context_files_project', 'context_files', ['project_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_goals_project', 'goals', ['project_id'], unique=False)
    op.create_table('orchestrator_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'orchestrator')", name='ck_orch_messages_role'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orch_messages_project', 'orchestrator_messages', ['project_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('template_key', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('room_x', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('room_y', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_key'], ['team_templates.key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_teams_project', 'teams', ['project_id'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('role_instructions', sa.Text(), nullable=False),
    sa.Column('model_tier', sa.Text(), nullable=False),
    sa.Column('slot', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("model_tier IN ('strong', 'medium', 'light')", name='ck_agents_tier'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'name', name='uq_agents_team_name')
    )
    op.create_index('ix_agents_project', 'agents', ['project_id'], unique=False)
    op.create_index('ix_agents_team', 'agents', ['team_id'], unique=False)
    op.create_table('agent_memories',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('content_md', sa.Text(), server_default='', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_table('edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('from_agent_id', sa.UUID(), nullable=False),
    sa.Column('to_agent_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('max_iterations', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(type = 'review_loop' AND max_iterations BETWEEN 1 AND 10) OR (type = 'handoff' AND max_iterations IS NULL)", name='ck_edges_max_iterations'),
    sa.CheckConstraint("type IN ('handoff', 'review_loop')", name='ck_edges_type'),
    sa.CheckConstraint('from_agent_id <> to_agent_id', name='ck_edges_no_self'),
    sa.ForeignKeyConstraint(['from_agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_agent_id', 'to_agent_id', 'type', name='uq_edges_triple'),
    sa.UniqueConstraint('from_agent_id', name='uq_edges_one_outgoing')
    )
    op.create_index('ix_edges_project', 'edges', ['project_id'], unique=False)
    op.create_index('ix_edges_to_agent', 'edges', ['to_agent_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=True),
    sa.Column('origin', sa.Text(), nullable=False),
    sa.Column('parent_task_id', sa.UUID(), nullable=True),
    sa.Column('edge_id', sa.UUID(), nullable=True),
    sa.Column('loop_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('override_route', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), server_default='queued', nullable=False),
    sa.Column('engine', sa.Text(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('input_payload', sa.Text(), nullable=True),
    sa.Column('continuations', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('result_markdown', sa.Text(), nullable=True),
    sa.Column('awaiting_prompt', sa.Text(), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('attempt', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('model_used', sa.Text(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('tokens_out', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('est_cost_usd', sa.Numeric(precision=10, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('verification', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("engine IN ('crew', 'agent_sdk')", name='ck_tasks_engine'),
    sa.CheckConstraint("origin IN ('chat', 'edge', 'panel')", name='ck_tasks_origin'),
    sa.CheckConstraint("status IN ('idle', 'queued', 'working', 'blocked', 'needs-input', 'done', 'failed')", name='ck_tasks_status'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['edge_id'], ['edges.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_agent_status', 'tasks', ['agent_id', 'status'], unique=False)
    op.create_index('ix_tasks_goal', 'tasks', ['goal_id'], unique=False)
    op.create_index('ix_tasks_project_status', 'tasks', ['project_id', 'status'], unique=False)
    op.create_index('ix_tasks_user_created', 'tasks', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('uq_tasks_parent_edge', 'tasks', ['parent_task_id', 'edge_id'], unique=True, postgresql_where=sa.text('parent_task_id IS NOT NULL AND edge_id IS NOT NULL'))
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_project', 'notifications', ['project_id'], unique=False)
    op.create_index('ix_notifications_user_read_created', 'notifications', ['user_id', 'read', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('outputs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('mime', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_bytes', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(content IS NOT NULL) <> (content_bytes IS NOT NULL)', name='ck_outputs_one_content'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outputs_project', 'outputs', ['project_id'], unique=False)
    op.create_index('ix_outputs_task', 'outputs', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outputs_task', table_name='outputs')
    op.drop_index('ix_outputs_project', table_name='outputs')
    op.drop_table('outputs')
    op.drop_index('ix_notifications_user_read_created', table_name='notifications')
    op.drop_index('ix_notifications_project', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('uq_tasks_parent_edge', table_name='tasks', postgresql_where=sa.text('parent_task_id IS NOT NULL AND edge_id IS NOT NULL'))
    op.drop_index('ix_tasks_user_created', table_name='tasks')
    op.drop_index('ix_tasks_project_status', table_name='tasks')
    op.drop_index('ix_tasks_goal', table_name='tasks')
    op.drop_index('ix_tasks_agent_status', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_edges_to_agent', table_name='edges')
    op.drop_index('ix_edges_project', table_name='edges')
    op.drop_table('edges')
    op.drop_table('agent_memories')
    op.drop_index('ix_agents_team', table_name='agents')
    op.drop_index('ix_agents_project', table_name='agents')
    op.drop_table('agents')
    op.drop_index('ix_teams_project', table_name='teams')
    op.drop_table('teams')
    op.drop_index('ix_orch_messages_project', table_name='orchestrator_messages')
    op.drop_table('orchestrator_messages')
    op.drop_index('ix_goals_project', table_name='goals')
    op.drop_table('goals')
    op.drop_index('ix_context_files_project', table_name='context_files')
    op.drop_table('context_files')
    op.drop_table('agent_templates')
    op.drop_table('user_profiles')
    op.drop_table('team_templates')
    op.drop_index('ix_projects_user', table_name='projects')
    op.drop_table('projects')
    op.drop_table('config')
    # ### end Alembic commands ###
