"""widen est_cost_usd to 12,6

Revision ID: e9fd0d85cb5e
Revises: b1c7d1a4d159
Create Date: 2026-06-13 13:31:42.705277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9fd0d85cb5e'
down_revision: Union[str, Sequence[str], None] = 'b1c7d1a4d159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'est_cost_usd',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=12, scale=6),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'est_cost_usd',
               existing_type=sa.Numeric(precision=12, scale=6),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
